install.packages("data.table")
install.packages("ggplot2")
install.packages("reshape")
install.packages("gapminder")
install.packages("stringr")
install.packages("jsonlite")
install.packages("ecoCopula")
install.packages("ranger")
install.packages("dplyr")
install.packages("pdp")
install.packages("plyr")
install.packages("gridExtra")
install.packages("tidyr")
install.packages("igraph")
install.packages("ppcor")
install.packages("stats")
install.packages("gganimate")
install.packages("coda") # test convergence
install.packages("SpiecEasi")
install.packages("Matrix")

# for inla
install.packages("INLA")
install.packages("splancs")
install.packages("rgeos")
install.packages("reshape2")
install.packages("deldir")
install.packages("viridis")
install.packages("rnaturalearth")
install.packages("ggspatial")
install.packages("fields")
install.packages("viridisLite")
install.packages("RColorBrewer")
